# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: NuGetToolInstaller@1

- task: Bash@3
  inputs:
    filePath: 'pipelines/docker-wordpress.sh'

- task: CmdLine@2
  inputs:
    script: 'docker exec wordpress_wpcli wp theme install quark'


#- task: CmdLine@2
#  inputs:
#    script: |
#      sudo apt update
#      sudo apt-get install apache2
#      sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password mypassword'
#      sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password mypassword'
#      sudo apt-get -y install mysql-server
#      sudo apt install wordpress php libapache2-mod-php php-mysql

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

